typography_spectrum: 0.17243550735654883
color:
  brandStrength: 0.9148146439361211
  lightness: 0.677817590383278
  saturation: 0.04152511552603233
  rhythmicContrast: 0.026801991460678895
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
layout_spectrum: 0.05510497820923234
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@spinonthese.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bcd10dcc-1ca3-4227-8cd4-fe1c66287979.png
name: revolutionary wheels
navigation:
  - name: Buy your Fat Boys direct from our online Speed Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Meet the Fat Boys
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Will Fat Boys fit my bike?
    id: c6f47da0-9a59-49ca-9fe2-85a830be26a1
    type: content
  - name: Tubeless made easy
    id: afd169d9-30af-4e0e-9f53-87ea8e6f022a
    type: content
  - name: Speed Metal Custom bikes
    url: 'http://speedmetal.bike'
    type: external
  - name: 'See who''s spinning up their #FatBoys over on Instagram'
    url: 'https://www.instagram.com/explore/tags/spinonthese/'
    type: external
  - name: Spin TV is on right now! Watch us over on YouTube
    url: 'https://www.youtube.com/ridefullgas'
    type: external
  - name: Real Reviews from Real Riders
    url: 'https://ridefullgas.com/customer-reviews/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e082c2a7-07dd-42b3-bcb7-0f0bdae77010.png
title: Spin On These Fast Carbon Wheels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/76d14b28-fba4-43ab-bb67-1e6938b2a57d.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/76d14b28-fba4-43ab-bb67-1e6938b2a57d.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/74dee931-e5ab-46ce-ba98-bfd4f2b9d3f8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/74dee931-e5ab-46ce-ba98-bfd4f2b9d3f8.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Because life's too short for slow boring bikes, uncomfortable rides and zero
  grip. Why not spin on these Fat Boys instead to upgrade your ride with
  effortless speed, gut wrenching all-weather adhesion and truly sublime comfort
  over every rut & bump on road or trail. But there's more to these Fat Boys and
  the people who make 'em. You see, every wheel we produce is precision hand
  crafted in the UK specifically for just one rider - and that rider is YOU. It
  means wheels that are uniquely engineered with your requirements in mind, made
  to deliver the ride of your life. Then there's our pricing - Maker to Rider
  Direct. Which means never paying extra for other dudes to sit in between and
  add their cut. But it also means we're directly on hand whenever you need help
  or advice, any time before or after purchase. And who better to deliver
  support and answer your needs than the people who actually made your wheels?
  If you've never heard of Spin On These before, scroll down to find bike riders
  like you, already spinning up their Fat Boys, winning races and enjoying their
  rides like never before. Life's short and you deserve to enjoy your ride. The
  only question is: what are you waiting for? 
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Buy Fat Boys
  - type: external
    url: 'https://ridefullgas.com/customer-reviews/'
    label: Reviews
