layout_spectrum: 0.37582264471882126
typography_spectrum: 0.06656237901824683
color:
  brandStrength: 0.48845408566886245
  lightness: 0.003075812968637536
  saturation: 0.17862286840150557
  rhythmicContrast: 0.3286547439240177
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf679bd1-13d8-4cf9-8f3f-46027c991a47.png
name: '#SpinOnThese Fast Carbon Wheels'
navigation:
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Meet the Fat Boys
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Custom Speed Metal
    url: 'http://speedmetal.bike'
    type: external
  - name: Spin on Instagram
    url: 'https://www.instagram.com/spinonthese/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bed6f34-0ec8-4087-89ab-c5ae2c9a909f.png
title: Spin On These!  Fast Carbon Bike Wheels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FvIn0fmwpr98%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DvIn0fmwpr98&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FvIn0fmwpr98%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Juliet Elliott
          url: 'https://www.youtube.com/user/hellyeahstupidshit'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - fixed gear
        - cycling
        - dartmoor
        - fixie
        - fixed
        - bike
        - track bike
        - bicycle
        - biking
        - fix
        - juliet elliott
        - fixie girl
        - womens cycling
      description: >-
        Dave and I are lucky enough to live between the moors and the sea so we
        went for a pedal in our backyard, Dartmoor. NEW VIDEOS EVERY FRIDAY.
        PLEASE SUBSCRIBE, it really helps !
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=vIn0fmwpr98&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=vIn0fmwpr98&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=vIn0fmwpr98&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=vIn0fmwpr98&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=vIn0fmwpr98&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=vIn0fmwpr98'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=vIn0fmwpr98
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=vIn0fmwpr98
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/vIn0fmwpr98'
      title: 'Hinterlands | A fixed gear cycling film shot in Dartmoor, UK'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Life's too short to ride dull boring wheels. But with Fat Boy Rim you get it
  all. Effortless speed. Gut wrenching grip. Incredible comfort. Thanks to super
  wide aero profiles the Fat Boys from Spin Industries are a whole lot more
  wheel for your money. Every pair Spin Meister precision hand built in the
  heart of England with just one rider in mind: You! 
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Buy Me
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Ask Me
