layout_spectrum: 0.6220453727246252
typography_spectrum: 0.6070695368121239
color:
  brandStrength: 0.9289977151866412
  lightness: 0.3460974471478511
  saturation: 0.4865591040016659
  rhythmicContrast: 0.28039052531482783
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/701dab8b-c105-4079-b22a-83d5a7dbd266.png
name: Fat Boy Rim
navigation:
  - name: Shop For Speed
    url: 'http://ridefullgas.com/'
    type: external
  - name: Ride Custom! Speed Metal Titanium
    url: 'http://speedmetal.bike/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc4b3c02-a0dc-4731-8294-5def0bf8a0c9.png
title: Spin On These! Koppenberg Fat Boys
description: "Awesomely fast. Superior grip. Incredible comfort. Super wide. Koppenberg wheels from Spin Industries are hand built with passion and precision. Every one made right here in my Speed Shop in the heart of England. And built with just one specific rider in mind. You!\_"
purpose:
  - type: external
    url: 'http://ridefullgas.com/dm8-series-super-fat-boys-28mm-wide/'
    label: Buy Now
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/468e4531-a988-4777-b373-312a07b286dd.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/468e4531-a988-4777-b373-312a07b286dd.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
analytics:
  google: UA-31654273-3
