typography_spectrum: 0.06656237901824683
color:
  brandStrength: 0.48845408566886245
  lightness: 0.003075812968637536
  saturation: 0.17862286840150557
  rhythmicContrast: 0.3286547439240177
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
layout_spectrum: 0.37582264471882126
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf679bd1-13d8-4cf9-8f3f-46027c991a47.png
name: Spin On These Wheels
navigation:
  - name: Shop for Speed in our Speed Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Meet the Fat Boys
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Will Fat Boys fit my bike?
    id: c6f47da0-9a59-49ca-9fe2-85a830be26a1
    type: content
  - name: Tubeless made easy
    id: afd169d9-30af-4e0e-9f53-87ea8e6f022a
    type: content
  - name: Speed Metal Custom bikes
    url: 'http://speedmetal.bike'
    type: external
  - name: See who Spins on Instagram
    url: 'https://www.instagram.com/explore/tags/spinonthese/'
    type: external
  - name: Spin TV now on YouTube
    url: 'https://www.youtube.com/ridefullgas'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bed6f34-0ec8-4087-89ab-c5ae2c9a909f.png
title: Spin On These!  Fast Carbon Bike Wheels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/81612783-eca8-4ea8-9699-0d71e131ca2c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/81612783-eca8-4ea8-9699-0d71e131ca2c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Because life's too short for slow boring bikes with no comfort and even less
  grip. Instead, let Fat Boy Rim pamper you with effortless speed, gut wrenching
  all-weather grip and truly sublime comfort over every surface. And know that
  every Fat Boy wheel is precision hand made in the UK with just one rider in
  mind: You!
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Shop the Fat Boys
  - type: contact
    url: 'mailto:drew@spinonthese.com'
    label: Ask the Spin Meister
