layout_spectrum: 0.8585562462964565
typography_spectrum: 0.14069062210305935
color:
  brandStrength: 0.8037739050141214
  lightness: 0.31052670629851814
  saturation: 0.45816775495785816
  rhythmicContrast: 0.5946842602971425
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cca08189-f62a-404f-b499-c3582da98ef3.png
name: 'Hey! #FatBoy'
navigation:
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Fat Boy Wheels
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Custom Titanium & Carbon Frames
    url: 'http://speedmetal.bike'
    type: external
  - name: Connect On Instagram
    url: 'https://www.instagram.com/spinonthese/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bed6f34-0ec8-4087-89ab-c5ae2c9a909f.png
title: Life's too short to ride boring wheels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9bac4fb1-25db-4b82-a0d7-82075d26866f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9bac4fb1-25db-4b82-a0d7-82075d26866f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc794412-0ace-4ea6-b00a-ed1f49594963.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc794412-0ace-4ea6-b00a-ed1f49594963.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: "Effortless speed. Gut wrenching grip. Incredible comfort. Now you can have it all thanks to Fat Boy Rim's superior width.  Spin Industries Fat Boys are hand built with passion and precision. Every one made here in our Speed Shop in the heart of England. And built with just one specific rider in mind. You!\_ Demand more from your wheels."
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Shop
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Questions?
