layout_spectrum: 0.6220453727246252
typography_spectrum: 0.6070695368121239
color:
  brandStrength: 0.9289977151866412
  lightness: 0.3460974471478511
  saturation: 0.4865591040016659
  rhythmicContrast: 0.28039052531482783
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d201ed40-196b-4545-abc4-2423b36104d0.png
name: Fat Boy Rim
navigation:
  - name: Shop For Speed
    url: 'http://ridefullgas.com/'
    type: external
  - name: Ride Custom! Speed Metal Titanium
    url: 'http://speedmetal.bike/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dc4b3c02-a0dc-4731-8294-5def0bf8a0c9.png
title: Spin On These! Koppenberg Fat Boys
description: "Awesomely fast. Superior grip. Incredible comfort. Super wide. Koppenberg wheels from Spin Industries are hand built with passion and precision. Every one made right here at the Speed Shop, England. And built with just one specific rider in mind. You!\_"
purpose:
  - type: external
    url: 'http://ridefullgas.com/dm8-series-super-fat-boys-28mm-wide/'
    label: Buy Now
content: []
github: true
analytics:
  google: UA-31654273-3
