layout_spectrum: 0.37582264471882126
typography_spectrum: 0.06656237901824683
color:
  brandStrength: 0.48845408566886245
  lightness: 0.003075812968637536
  saturation: 0.17862286840150557
  rhythmicContrast: 0.3286547439240177
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf679bd1-13d8-4cf9-8f3f-46027c991a47.png
name: '#SpinOnThese Fast Carbon Wheels'
navigation:
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Meet the Fat Boys
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Custom Speed Metal
    url: 'http://speedmetal.bike'
    type: external
  - name: Spin on Instagram
    url: 'https://www.instagram.com/spinonthese/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bed6f34-0ec8-4087-89ab-c5ae2c9a909f.png
title: Spin On These!  Fast Carbon Bike Wheels
content: []
description: >-
  Life's too short to ride dull boring wheels. But with Fat Boy Rim you get it
  all. Effortless speed. Gut wrenching grip. Incredible comfort. Thanks to super
  wide aero profiles the Fat Boys from Spin Industries are a whole lot more
  wheel for your money. Every pair Spin Meister precision hand built in the
  heart of England with just one rider in mind: You! 
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Buy Me
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Ask Me
