typography_spectrum: 0.3394709033930287
color:
  brandStrength: 0.8091196354962702
  lightness: 0.3102084231663422
  saturation: 0.45345386282337996
  rhythmicContrast: 0.5930179002326866
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
layout_spectrum: 0.6256294064650699
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b12b613b-4f7e-4f03-b46e-d1bb5978f80e.png
name: '#SpinOnThese #WinOnThese'
navigation:
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Fat Boy Wheels
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Custom Titanium & Carbon Frames
    url: 'http://speedmetal.bike'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/spinonthese/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bed6f34-0ec8-4087-89ab-c5ae2c9a909f.png
title: Spin On These Koppenberg Fat Boys
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8b9e0119-8d83-45e3-b975-25fff72d53b6.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8b9e0119-8d83-45e3-b975-25fff72d53b6.gif
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: "Effortless speed. Gut wrenching grip. Incredible comfort. It's all down to these Fat Boys' superior width. Koppenberg wheels from Spin Industries are hand built with passion and precision. Every one made here in my Speed Shop in the heart of England. And built with just one specific rider in mind. You!\_"
purpose:
  - type: external
    url: 'http://ridefullgas.com/dm8-series-super-fat-boys-28mm-wide/'
    label: Buy Now
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Questions?
