layout_spectrum: 0.05510497820923234
typography_spectrum: 0.17243550735654883
color:
  brandStrength: 0.9148146439361211
  lightness: 0.677817590383278
  saturation: 0.04152511552603233
  rhythmicContrast: 0.026801991460678895
  brandColors:
    - '#050505'
    - '#373739'
    - '#E9E01B'
    - '#6E6E6E'
    - '#D7D7D7'
github: true
analytics:
  google: UA-31654273-3
author:
  name: The Spin Meister
  email: spinfo@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bcd10dcc-1ca3-4227-8cd4-fe1c66287979.png
name: revolutionary wheels
navigation:
  - name: Shop for Fat Boys & all things fast in our online Speed Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Meet the Fat Boys
    id: 472d1184-2d33-4a73-b4ec-e77a58d2c5be
    type: content
  - name: Will Fat Boys fit my bike?
    id: c6f47da0-9a59-49ca-9fe2-85a830be26a1
    type: content
  - name: Tubeless made easy
    id: afd169d9-30af-4e0e-9f53-87ea8e6f022a
    type: content
  - name: Speed Metal Custom bikes
    url: 'http://speedmetal.bike'
    type: external
  - name: 'See who''s spinning up their #FatBoys over on Instagram'
    url: 'https://www.instagram.com/explore/tags/spinonthese/'
    type: external
  - name: Spin TV is on right now! Watch us over on YouTube
    url: 'https://www.youtube.com/ridefullgas'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e082c2a7-07dd-42b3-bcb7-0f0bdae77010.png
title: Spin On These Fast Carbon Wheels
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/81612783-eca8-4ea8-9699-0d71e131ca2c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/81612783-eca8-4ea8-9699-0d71e131ca2c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  ...because life's too short for slow boring bikes, uncomfortable rides and
  zero grip. Spin on these Fat Boys instead and upgrade your ride to effortless
  speed, gut wrenching adhesion in all weathers and truly sublime comfort over
  any type of surface. But there's more to these Fat Boys and the people who
  make 'em. You see, every wheel is precision hand crafted in the UK
  specifically for just one rider - that's You! That means wheels uniquely
  engineered with your requirements in mind that deliver the ride of your life.
  Then there's our Maker to Rider Direct pricing which means you're never paying
  extra for other dudes to get in between us. And it means when you need help or
  advice - before or after purchase - who better to ask than the people who
  actually made your wheels. If you've never heard of us before, scroll down to
  find riders like you who're already spinning up their Fat Boys and enjoying
  the ride like never before. One day we hope to help transform your ride too -
  thanks for riding by!
purpose:
  - type: external
    url: 'http://ridefullgas.com/wheels/'
    label: Buy Fat Boys
  - type: contact
    url: 'mailto:drew@spinonthese.com'
    label: Ask the Spin Meister
